// customer-lifecycle.ts — deterministic lifecycle stage classifier.
//
// ARCHITECTURAL NOTE (Decision 1):
// This is a pure function. Same input → same output, no side effects.
// The result is written to customer_inferred_state.lifecycle_stage (a cache).
// It is NEVER canonical — it can always be regenerated by calling this
// function with the current MaterializedCustomer snapshot.

import type { Database } from "@lapsed/db";

export type LifecycleStage = Database["public"]["Enums"]["lifecycle_stage"];

/**
 * Minimal customer snapshot needed for lifecycle classification.
 * Sourced from the materialised `customers` row or from a replay of order_events.
 */
export interface CustomerSnapshot {
  totalOrderCount: number;
  lastOrderDaysAgo: number | null;  // null = no orders
  firstOrderDaysAgo: number | null; // null = no orders
  ordersInPast12Months: number;
  previousLifecycleStage?: LifecycleStage | null; // from the last scoring event payload
  daysSinceLastScoredAsLapsed?: number | null;    // null = was never classified lapsed
  engagementEventsInPast180Days: number;          // customer_events count (non-order types)
}

/**
 * Classify a customer's lifecycle stage deterministically from their order history
 * and prior classification.
 *
 * Rules (applied in order — first match wins):
 *
 * 1. churned   — last order > 365 days ago AND no engagement events in past 180 days
 * 2. won_back  — current observable data would be `engaged` AND was classified as
 *                `lapsed` at any point in the past 90 days
 * 3. lapsed    — last order > 180 days ago
 * 4. at_risk   — last order 60–180 days ago (exclusive) AND was previously `engaged`
 * 5. engaged   — last order ≤ 60 days ago AND ≥ 2 orders in past 12 months
 * 6. new       — first order ≤ 30 days ago AND exactly 1 order total
 * 7. lapsed    — fallback for customers who don't fit 1–6
 *                (e.g., 1 order > 30 days ago but ≤ 180 days, not yet at_risk)
 */
export function classifyLifecycle(customer: CustomerSnapshot): LifecycleStage {
  const {
    totalOrderCount,
    lastOrderDaysAgo,
    firstOrderDaysAgo,
    ordersInPast12Months,
    previousLifecycleStage,
    daysSinceLastScoredAsLapsed,
    engagementEventsInPast180Days,
  } = customer;

  // No orders at all → not enough data to classify; treat as new if very recent
  // or lapsed if no activity.
  if (totalOrderCount === 0 || lastOrderDaysAgo === null || firstOrderDaysAgo === null) {
    return "lapsed";
  }

  // Rule 1: churned — oldest possible state, check first.
  if (lastOrderDaysAgo > 365 && engagementEventsInPast180Days === 0) {
    return "churned";
  }

  // For won_back we need to know the "base" stage the customer would currently be in
  // without prior state. Compute it optimistically first.
  const baseStage = computeBaseStage({
    totalOrderCount,
    lastOrderDaysAgo,
    firstOrderDaysAgo,
    ordersInPast12Months,
    previousLifecycleStage,
  });

  // Rule 2: won_back — base stage is `engaged` AND was `lapsed` within past 90 days.
  if (
    baseStage === "engaged" &&
    previousLifecycleStage === "lapsed" &&
    daysSinceLastScoredAsLapsed !== null &&
    daysSinceLastScoredAsLapsed <= 90
  ) {
    return "won_back";
  }

  return baseStage;
}

function computeBaseStage(customer: {
  totalOrderCount: number;
  lastOrderDaysAgo: number;
  firstOrderDaysAgo: number;
  ordersInPast12Months: number;
  previousLifecycleStage?: LifecycleStage | null;
}): LifecycleStage {
  const {
    totalOrderCount,
    lastOrderDaysAgo,
    firstOrderDaysAgo,
    ordersInPast12Months,
    previousLifecycleStage,
  } = customer;

  // Rule 3: lapsed — last order > 180 days ago.
  if (lastOrderDaysAgo > 180) {
    return "lapsed";
  }

  // Rule 4: at_risk — 60 < lastOrderDaysAgo ≤ 180 AND was previously engaged.
  if (lastOrderDaysAgo > 60 && previousLifecycleStage === "engaged") {
    return "at_risk";
  }

  // Rule 5: engaged — last order ≤ 60 days ago AND ≥ 2 orders in past 12 months.
  if (lastOrderDaysAgo <= 60 && ordersInPast12Months >= 2) {
    return "engaged";
  }

  // Rule 6: new — first order ≤ 30 days ago AND exactly 1 order total.
  if (firstOrderDaysAgo <= 30 && totalOrderCount === 1) {
    return "new";
  }

  // Rule 7: fallback lapsed — covers single-purchase customers > 30 days ago,
  // at-risk customers without a prior engaged classification, etc.
  return "lapsed";
}
