import type { DemoFixtures } from "./types";

export const v1: DemoFixtures = {
  version: 1,
  merchant: {
    id: "mer_bedrock_demo",
    shopDomain: "bedrock-apothecary.myshopify.com",
    shopName: "Bedrock Apothecary",
    shopInitials: "BA",
    plan: "growth",
    planLabel: "Growth · 25k msgs",
    monthlyMessageQuota: 25000,
    monthlyMessagesUsed: 8742,
    brandVoice:
      "Warm, knowledgeable, unhurried. Australian English spelling. Speaks like a trusted skincare advisor — never pushy, always precise.",
    optOutKeywords: ["STOP", "STOPALL", "UNSUBSCRIBE", "QUIT", "END", "CANCEL"],
    ownerName: "Sarah Chen",
    ownerInitials: "SC",
    installedAt: "2026-02-12T08:30:00Z",
    totalLapsedCount: 847,
    weeklyLapsedDelta: 53,
    reactivationRate: 6.4,
    reactivationRateDeltaPp: 1.2,
  },

  lapsedCustomers: [
    {
      id: "cust_001",
      initials: "AM",
      firstName: "Annika",
      lastName: "Mortensen",
      tier: "vip",
      status: "lapsed",
      lifetimeValue: 1842,
      orderCount: 11,
      lastOrderAt: "2025-11-18T11:20:00Z",
      lastOrderDaysAgo: 181,
      reactivationScore: 87,
      cadenceDays: 32,
      preferredCategory: "Serums & treatments",
      orderHistory: [
        {
          id: "ord_001a",
          placedAt: "2025-11-18T11:20:00Z",
          total: 184,
          lineCount: 3,
          topProduct: "Vitamin C Serum 30ml",
        },
        {
          id: "ord_001b",
          placedAt: "2025-10-11T09:40:00Z",
          total: 124,
          lineCount: 2,
          topProduct: "Niacinamide Serum",
        },
        {
          id: "ord_001c",
          placedAt: "2025-09-14T14:05:00Z",
          total: 219,
          lineCount: 4,
          topProduct: "Retinol Night Cream",
        },
      ],
    },
    {
      id: "cust_002",
      initials: "JT",
      firstName: "James",
      lastName: "Tulloch",
      tier: "repeat",
      status: "lapsed",
      lifetimeValue: 548,
      orderCount: 4,
      lastOrderAt: "2026-02-01T16:30:00Z",
      lastOrderDaysAgo: 106,
      reactivationScore: 72,
      cadenceDays: 45,
      preferredCategory: "Moisturisers",
      orderHistory: [
        {
          id: "ord_002a",
          placedAt: "2026-02-01T16:30:00Z",
          total: 98,
          lineCount: 1,
          topProduct: "Daily SPF Moisturiser",
        },
        {
          id: "ord_002b",
          placedAt: "2025-12-10T10:00:00Z",
          total: 156,
          lineCount: 2,
          topProduct: "Hydra-Boost Gel",
        },
      ],
    },
    {
      id: "cust_003",
      initials: "PL",
      firstName: "Priya",
      lastName: "Lakshmi",
      tier: "vip",
      status: "reactivating",
      lifetimeValue: 2310,
      orderCount: 16,
      lastOrderAt: "2026-01-28T08:00:00Z",
      lastOrderDaysAgo: 110,
      reactivationScore: 91,
      cadenceDays: 28,
      preferredCategory: "Serums & treatments",
      orderHistory: [
        {
          id: "ord_003a",
          placedAt: "2026-01-28T08:00:00Z",
          total: 248,
          lineCount: 4,
          topProduct: "Peptide Complex Serum",
        },
        {
          id: "ord_003b",
          placedAt: "2025-12-28T15:15:00Z",
          total: 189,
          lineCount: 3,
          topProduct: "AHA/BHA Exfoliant",
        },
      ],
    },
    {
      id: "cust_004",
      initials: "WN",
      firstName: "Wendy",
      lastName: "Nakamura",
      tier: "repeat",
      status: "lapsed",
      lifetimeValue: 430,
      orderCount: 3,
      lastOrderAt: "2025-12-20T19:45:00Z",
      lastOrderDaysAgo: 149,
      reactivationScore: 61,
      cadenceDays: 55,
      preferredCategory: "Cleansers",
      orderHistory: [
        {
          id: "ord_004a",
          placedAt: "2025-12-20T19:45:00Z",
          total: 64,
          lineCount: 1,
          topProduct: "Gentle Foam Cleanser",
        },
        {
          id: "ord_004b",
          placedAt: "2025-10-26T12:30:00Z",
          total: 112,
          lineCount: 2,
          topProduct: "Micellar Water 400ml",
        },
      ],
    },
    {
      id: "cust_005",
      initials: "BK",
      firstName: "Ben",
      lastName: "Khatri",
      tier: "new",
      status: "churned",
      lifetimeValue: 87,
      orderCount: 1,
      lastOrderAt: "2025-09-03T10:00:00Z",
      lastOrderDaysAgo: 257,
      reactivationScore: 28,
      cadenceDays: 0,
      preferredCategory: "Sunscreen",
      orderHistory: [
        {
          id: "ord_005a",
          placedAt: "2025-09-03T10:00:00Z",
          total: 87,
          lineCount: 1,
          topProduct: "SPF 50+ Sport Sunscreen",
        },
      ],
    },
    {
      id: "cust_006",
      initials: "EO",
      firstName: "Emma",
      lastName: "O'Brien",
      tier: "vip",
      status: "converted",
      lifetimeValue: 3140,
      orderCount: 22,
      lastOrderAt: "2026-05-10T14:20:00Z",
      lastOrderDaysAgo: 8,
      reactivationScore: 95,
      cadenceDays: 21,
      preferredCategory: "Serums & treatments",
      orderHistory: [
        {
          id: "ord_006a",
          placedAt: "2026-05-10T14:20:00Z",
          total: 312,
          lineCount: 5,
          topProduct: "Vitamin C Serum 30ml",
        },
        {
          id: "ord_006b",
          placedAt: "2026-04-12T11:00:00Z",
          total: 189,
          lineCount: 3,
          topProduct: "Retinol Night Cream",
        },
      ],
    },
    {
      id: "cust_007",
      initials: "RD",
      firstName: "Rachel",
      lastName: "Davies",
      tier: "repeat",
      status: "lapsed",
      lifetimeValue: 690,
      orderCount: 5,
      lastOrderAt: "2026-02-15T09:10:00Z",
      lastOrderDaysAgo: 92,
      reactivationScore: 68,
      cadenceDays: 42,
      preferredCategory: "Moisturisers",
      orderHistory: [
        {
          id: "ord_007a",
          placedAt: "2026-02-15T09:10:00Z",
          total: 134,
          lineCount: 2,
          topProduct: "Ceramide Rich Moisturiser",
        },
      ],
    },
    {
      id: "cust_008",
      initials: "SM",
      firstName: "Sophie",
      lastName: "Moreau",
      tier: "vip",
      status: "lapsed",
      lifetimeValue: 1680,
      orderCount: 9,
      lastOrderAt: "2025-12-01T16:40:00Z",
      lastOrderDaysAgo: 168,
      reactivationScore: 79,
      cadenceDays: 38,
      preferredCategory: "Eye care",
      orderHistory: [
        {
          id: "ord_008a",
          placedAt: "2025-12-01T16:40:00Z",
          total: 224,
          lineCount: 3,
          topProduct: "Peptide Eye Cream",
        },
      ],
    },
    {
      id: "cust_009",
      initials: "LH",
      firstName: "Lily",
      lastName: "Haddad",
      tier: "vip",
      status: "lapsed",
      lifetimeValue: 2180,
      orderCount: 14,
      lastOrderAt: "2025-12-08T13:00:00Z",
      lastOrderDaysAgo: 161,
      reactivationScore: 82,
      cadenceDays: 35,
      preferredCategory: "Serums & treatments",
      orderHistory: [
        {
          id: "ord_009a",
          placedAt: "2025-12-08T13:00:00Z",
          total: 198,
          lineCount: 3,
          topProduct: "Vitamin C Serum 30ml",
        },
        {
          id: "ord_009b",
          placedAt: "2025-11-02T10:20:00Z",
          total: 246,
          lineCount: 4,
          topProduct: "Peptide Complex Serum",
        },
      ],
    },
    {
      id: "cust_010",
      initials: "MT",
      firstName: "Mia",
      lastName: "Tanaka",
      tier: "repeat",
      status: "lapsed",
      lifetimeValue: 520,
      orderCount: 4,
      lastOrderAt: "2026-01-14T08:50:00Z",
      lastOrderDaysAgo: 124,
      reactivationScore: 64,
      cadenceDays: 48,
      preferredCategory: "Cleansers",
      orderHistory: [
        {
          id: "ord_010a",
          placedAt: "2026-01-14T08:50:00Z",
          total: 79,
          lineCount: 1,
          topProduct: "Balancing Toner 200ml",
        },
      ],
    },
  ],

  campaigns: [
    {
      id: "demo_cam_001",
      name: "30-day dormant — skincare essentials",
      meta: "312 customers · launched 18 days ago",
      status: "live",
      statusLabel: "Live",
      audienceSize: 312,
      sentMessages: 289,
      responseRate: 0.41,
      conversionRate: 0.082,
      recoveredRevenue: 19840,
      recoveredOrders: 24,
      recoveredRevenueDisplay: "$19,840",
      launchedAt: "2026-04-30T23:00:00Z",
      scheduledFor: null,
      pausedAt: null,
      completedAt: null,
      audienceBreakdown: [
        { label: "VIP (4+ orders, LTV $800+)", count: 87 },
        { label: "Repeat buyers (2–3 orders)", count: 168 },
        { label: "Recent singles (1 order, high LTV)", count: 57 },
      ],
      timeline: [
        { at: "2026-04-30T23:00:00Z", label: "Campaign launched · 289 messages queued" },
        { at: "2026-05-01T09:14:00Z", label: "First restoration — $248 attributed to Priya L." },
        { at: "2026-05-08T14:22:00Z", label: "Arm B outperforming Arm A — 9.1% vs 6.8% conversion" },
        { at: "2026-05-18T11:00:00Z", label: "24 restored orders · $19,840 to date" },
      ],
    },
    {
      id: "demo_cam_002",
      name: "VIP re-engagement — 90+ days silent",
      meta: "98 customers · paused 3 days ago",
      status: "paused",
      statusLabel: "Paused",
      audienceSize: 98,
      sentMessages: 91,
      responseRate: 0.34,
      conversionRate: 0.066,
      recoveredRevenue: 11620,
      recoveredOrders: 8,
      recoveredRevenueDisplay: "$11,620",
      launchedAt: "2026-04-18T23:00:00Z",
      scheduledFor: null,
      pausedAt: "2026-05-15T09:30:00Z",
      completedAt: null,
      audienceBreakdown: [
        { label: "VIP tier 1 (LTV $2,000+)", count: 34 },
        { label: "VIP tier 2 (LTV $1,000–$2,000)", count: 64 },
      ],
      timeline: [
        { at: "2026-04-18T23:00:00Z", label: "Campaign launched · 91 messages queued" },
        { at: "2026-04-19T14:40:00Z", label: "First restoration — $312 attributed to Emma O." },
        { at: "2026-05-15T09:30:00Z", label: "Paused — opt-out rate reached 4.3% (threshold: 4%)" },
      ],
    },
    {
      id: "demo_cam_003",
      name: "Deep lapsed — 6-month win-back",
      meta: "156 customers · completed 14 days ago",
      status: "draft",
      statusLabel: "Completed",
      audienceSize: 156,
      sentMessages: 149,
      responseRate: 0.19,
      conversionRate: 0.034,
      recoveredRevenue: 15640,
      recoveredOrders: 10,
      recoveredRevenueDisplay: "$15,640",
      launchedAt: "2026-04-01T23:00:00Z",
      scheduledFor: null,
      pausedAt: null,
      completedAt: "2026-05-04T23:59:00Z",
      audienceBreakdown: [
        { label: "Lapsed 6–12 months, repeat buyers", count: 102 },
        { label: "Lapsed 12+ months, VIP history", count: 54 },
      ],
      timeline: [
        { at: "2026-04-01T23:00:00Z", label: "Campaign launched · 149 messages queued" },
        { at: "2026-04-02T16:00:00Z", label: "First restoration — $188 attributed to Annika M." },
        { at: "2026-05-04T23:59:00Z", label: "Attribution window closed · 10 restored orders" },
      ],
    },
  ],

  conversations: [
    {
      id: "demo_conv_001",
      initials: "EO",
      customerName: "Emma O'Brien",
      campaignName: "VIP re-engagement",
      time: "2h ago",
      preview: "Oh that's lovely, I've been meaning to restock my serum anyway",
      tagTone: "converted",
      tagLabel: "Restored",
      status: "converted",
      attributedRevenue: 312,
      messages: [
        {
          id: "msg_001a",
          role: "ai",
          body: "Hi Emma — it's been a while since we've seen you at Bedrock. We'd love to welcome you back with 15% off your next order. Reply YES to claim, or STOP to opt out.",
          sentAt: "2026-04-19T09:00:00Z",
        },
        {
          id: "msg_001b",
          role: "customer",
          body: "Oh that's lovely, I've been meaning to restock my serum anyway",
          sentAt: "2026-04-19T09:14:00Z",
        },
        {
          id: "msg_001c",
          role: "ai",
          body: "Wonderful! Your 15% discount code is VIPBACK15 — valid for 7 days. I'd recommend the Vitamin C Serum; it pairs beautifully with your usual retinol routine.",
          sentAt: "2026-04-19T09:15:00Z",
        },
        {
          id: "msg_001d",
          role: "customer",
          body: "Perfect thank you, ordering now",
          sentAt: "2026-04-19T10:02:00Z",
        },
      ],
    },
    {
      id: "demo_conv_002",
      initials: "PL",
      customerName: "Priya Lakshmi",
      campaignName: "30-day dormant",
      time: "Yesterday",
      preview: "What's the difference between the two serums?",
      tagTone: "active",
      tagLabel: "Active",
      status: "active",
      attributedRevenue: null,
      messages: [
        {
          id: "msg_002a",
          role: "ai",
          body: "Hi Priya — your peptide serum is likely running low. Ready to restock? Reply YES to get free shipping on your next order.",
          sentAt: "2026-05-17T10:00:00Z",
        },
        {
          id: "msg_002b",
          role: "customer",
          body: "What's the difference between the two serums?",
          sentAt: "2026-05-17T11:40:00Z",
        },
        {
          id: "msg_002c",
          role: "ai",
          body: "Great question. The Peptide Complex targets fine lines and firmness — it's what you've been using. The Vitamin C Serum brightens and protects. Many customers use both: Vitamin C in the morning, peptides at night. Happy to send a Vitamin C sample if you'd like to try?",
          sentAt: "2026-05-17T11:41:00Z",
        },
      ],
    },
    {
      id: "demo_conv_003",
      initials: "SM",
      customerName: "Sophie Moreau",
      campaignName: "Deep lapsed win-back",
      time: "1 week ago",
      preview: "Yes please, that sounds great — can I also ask about the eye cream?",
      tagTone: "active",
      tagLabel: "Engaged",
      status: "active",
      attributedRevenue: null,
      messages: [
        {
          id: "msg_003a",
          role: "ai",
          body: "Hi Sophie — it's been almost 6 months. We'd love to welcome you back with 15% off and a complimentary eye cream sample.",
          sentAt: "2026-05-11T10:00:00Z",
        },
        {
          id: "msg_003b",
          role: "customer",
          body: "Yes please, that sounds great — can I also ask about the eye cream?",
          sentAt: "2026-05-11T12:45:00Z",
        },
        {
          id: "msg_003c",
          role: "ai",
          body: "Of course! The Peptide Eye Cream is formulated for the delicate under-eye area — caffeine to de-puff, peptides to firm. It's one of our most re-ordered products. Want me to include a full size in your next order at the discounted rate?",
          sentAt: "2026-05-11T12:46:00Z",
        },
      ],
    },
    {
      id: "demo_conv_004",
      initials: "AM",
      customerName: "Annika Mortensen",
      campaignName: "Deep lapsed win-back",
      time: "3 days ago",
      preview: "I've actually moved to another brand but thanks",
      tagTone: "churned",
      tagLabel: "Churned",
      status: "stalled",
      attributedRevenue: null,
      messages: [
        {
          id: "msg_004a",
          role: "ai",
          body: "Hi Annika — it's been 6 months. We miss you! We'd love to win you back with a free Vitamin C sample on your next order.",
          sentAt: "2026-04-02T10:00:00Z",
        },
        {
          id: "msg_004b",
          role: "customer",
          body: "I've actually moved to another brand but thanks",
          sentAt: "2026-04-02T14:22:00Z",
        },
      ],
    },
    {
      id: "demo_conv_005",
      initials: "JT",
      customerName: "James Tulloch",
      campaignName: "30-day dormant",
      time: "5 days ago",
      preview: "No thanks, I'm good for now",
      tagTone: "stalled",
      tagLabel: "No reply needed",
      status: "stalled",
      attributedRevenue: null,
      messages: [
        {
          id: "msg_005a",
          role: "ai",
          body: "Hi James — your Daily SPF Moisturiser should be running low around now. Want to restock with free shipping?",
          sentAt: "2026-05-13T09:00:00Z",
        },
        {
          id: "msg_005b",
          role: "customer",
          body: "No thanks, I'm good for now",
          sentAt: "2026-05-13T16:10:00Z",
        },
      ],
    },
    {
      id: "demo_conv_006",
      initials: "WN",
      customerName: "Wendy Nakamura",
      campaignName: "30-day dormant",
      time: "1 week ago",
      preview: "STOP",
      tagTone: "churned",
      tagLabel: "Opted out",
      status: "opted_out",
      attributedRevenue: null,
      messages: [
        {
          id: "msg_006a",
          role: "ai",
          body: "Hi Wendy — your Gentle Foam Cleanser may be running low. Reply YES for a restock reminder with free shipping.",
          sentAt: "2026-05-11T09:30:00Z",
        },
        {
          id: "msg_006b",
          role: "customer",
          body: "STOP",
          sentAt: "2026-05-11T10:01:00Z",
        },
        {
          id: "msg_006c",
          role: "ai",
          body: "You've been unsubscribed and won't receive further messages from Bedrock Apothecary via SMS. Reply START to re-subscribe at any time.",
          sentAt: "2026-05-11T10:01:00Z",
        },
      ],
    },
  ],

  attribution: {
    periodStart: "2026-04-18T00:00:00Z",
    periodEnd: "2026-05-18T00:00:00Z",
    totalRestoredRevenue: 47100,
    incrementalRevenue: 31200,
    ciLow: 24100,
    ciHigh: 38300,
    incrementalityPct: 66,
    totalRestoredOrders: 42,
    vsPreviousPeriodPct: 18,
    byDay: [
      { date: "2026-04-18", recoveredRevenue: 0 },
      { date: "2026-04-19", recoveredRevenue: 312 },
      { date: "2026-04-20", recoveredRevenue: 840 },
      { date: "2026-04-21", recoveredRevenue: 0 },
      { date: "2026-04-22", recoveredRevenue: 1240 },
      { date: "2026-04-23", recoveredRevenue: 680 },
      { date: "2026-04-24", recoveredRevenue: 0 },
      { date: "2026-04-25", recoveredRevenue: 920 },
      { date: "2026-04-26", recoveredRevenue: 1480 },
      { date: "2026-04-27", recoveredRevenue: 620 },
      { date: "2026-04-28", recoveredRevenue: 0 },
      { date: "2026-04-29", recoveredRevenue: 1840 },
      { date: "2026-04-30", recoveredRevenue: 1120 },
      { date: "2026-05-01", recoveredRevenue: 2480 },
      { date: "2026-05-02", recoveredRevenue: 1640 },
      { date: "2026-05-03", recoveredRevenue: 880 },
      { date: "2026-05-04", recoveredRevenue: 3200 },
      { date: "2026-05-05", recoveredRevenue: 1860 },
      { date: "2026-05-06", recoveredRevenue: 920 },
      { date: "2026-05-07", recoveredRevenue: 2140 },
      { date: "2026-05-08", recoveredRevenue: 3480 },
      { date: "2026-05-09", recoveredRevenue: 1720 },
      { date: "2026-05-10", recoveredRevenue: 4120 },
      { date: "2026-05-11", recoveredRevenue: 2840 },
      { date: "2026-05-12", recoveredRevenue: 1440 },
      { date: "2026-05-13", recoveredRevenue: 3680 },
      { date: "2026-05-14", recoveredRevenue: 2160 },
      { date: "2026-05-15", recoveredRevenue: 1920 },
      { date: "2026-05-16", recoveredRevenue: 2880 },
      { date: "2026-05-17", recoveredRevenue: 3440 },
      { date: "2026-05-18", recoveredRevenue: 1640 },
    ],
    byCampaign: [
      {
        campaignId: "demo_cam_001",
        campaignName: "30-day dormant",
        recoveredRevenue: 19840,
        incrementalRevenue: 14200,
        recoveredOrders: 24,
        ciLow: 10800,
        ciHigh: 17600,
      },
      {
        campaignId: "demo_cam_002",
        campaignName: "VIP re-engagement",
        recoveredRevenue: 11620,
        incrementalRevenue: 9400,
        recoveredOrders: 8,
        ciLow: 6900,
        ciHigh: 11900,
      },
      {
        campaignId: "demo_cam_003",
        campaignName: "Deep lapsed win-back",
        recoveredRevenue: 15640,
        incrementalRevenue: 7600,
        recoveredOrders: 10,
        ciLow: 5200,
        ciHigh: 10000,
      },
    ],
  },

  billing: {
    currentPlan: "growth",
    currentPlanLabel: "Growth · 25k msgs",
    currentPlanPrice: 799,
    monthlyMessageQuota: 25000,
    monthlyMessagesUsed: 8742,
    renewsAt: "2026-06-12T08:30:00Z",
    paymentMethodLast4: "4242",
  },
};
